config/routes.rb
Acompanysite::Application.routes.draw do
  root to: 'pages#home'
  get 'solutions' => 'pages#solutions'
  get 'technology' => 'pages#technology'
  get 'services' => 'pages#services'
  get 'contact' => 'pages#contact'

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :pages, :posts
  end

end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController


  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < Admin::BaseController

    def index

    end

  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < Admin::BaseController

    def index

    end

  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::BaseController

    def index

    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Keocko.com"
    #@slideshow_content = [
    #     {h1: 'Human detection', h2: 'Real-time consumer statistics<br /> - measurable efficiency'.html_safe, image: 'keocko_slide1.jpg'},
    #     {h1: 'Human Sensor', h2: 'has made the dream of marketing experts<br /> come true!'.html_safe, image: 'keocko_slide2.jpg'},
    #     {h1: 'Our reports', h2: 'are about Your customers', image: 'keocko_slide3.jpg'},
    #     {h1: 'Hourly rate of € 0.09', h2: 'You can decrease or replace the largest part<br /> of your expenses: live labor!'.html_safe, image: 'keocko_slide6.jpg'},
    #     ]
    @slideshow_content = [
        {h1: '', h2: '', image:'slider1.jpg'},
        {h1: '', h2: '', image:'slider2.jpg'},
        {h1: '', h2: '', image:'slider3.jpg'},
        {h1: '', h2: '', image:'slider4.jpg'},
        {h1: '', h2: '', image:'slider5.jpg'},
    ]

     @slideshow_length = @slideshow_content.length

  end

  def solutions

  end

  def technology

  end

  def services

  end

  def contact

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/views/admin/dashboard/index.html.haml
%h1 Dashboard Index

app/views/admin/pages/index.html.haml
%h1 Pages Admin

app/views/admin/posts/index.html.haml
%h1 Posts Admin

app/views/layouts/_footer.html.haml
%footer
  .container
    %p.middle
      ="&copy Keocko 2013".html_safe

app/views/layouts/_header.html.haml
.container
  .row
    .span5.pull-left
      .logo
        =link_to image_tag('keocko.png'), '#'
%header
  .navbar-wrapper
    .container
      .navbar.navbar-inverse
        %nav.navbar-inner#navmenu{role: 'navigation'}
          %ul.nav
            %li=link_to 'HOME', root_path
            %li=link_to 'SOLUTIONS', solutions_path
            %li=link_to 'TECHNOLOGY', technology_path
            %li=link_to 'SERVICES', services_path
            %li=link_to 'CONTACT US', contact_path

app/views/layouts/_main.html.haml
#main{role: "main"}
  = yield

app/views/layouts/_navigation.html.haml
=link_to 'Company Name', root_path, class: 'brand'
%ul.nav
  %li.active=link_to 'Solutions', solutions_path
  %li=link_to 'Technology', 'pages'
  %li=link_to 'Services', '#'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "A Company Site"
    %meta{content: "The Human Sensor", name: "description"}
    %meta{content: "Zoltan Debre", name: "author"}
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/header'
    = render 'layouts/main'
    = render 'layouts/footer'

app/views/pages/contact.html.haml
- content_for(:title, "Keocko.com - Contact")
.article-wrapper
  .container{style: 'max-width: 500px;'}
    :markdown
      ##Contact details

      >Phone:

      >E-mail:

app/views/pages/home.html.haml
- content_for(:title, "Keocko.com")
#myCarousel.carousel.slide
  %ol.carousel-indicators
    %li.active{data: {target: '#myCarousel', slide_to: '0'}}
    -i=1
    -(@slideshow_length-1).times do
      %li{data: {target: '#myCarousel', slide_to: "#{i}"}}
      -i+=1
  .carousel-inner
    -i=0
    -@slideshow_content.each do |content|
      .item{class: ('active' if (i==0))}
        =image_tag content[:image]
        .container
          .carousel-caption
            %h1=content[:h1]
            %p.lead=content[:h2]
      -i+=1
  %a.carousel-control.left{href: "#myCarousel", "data-slide" => 'prev'} &lsaquo;
  %a.carousel-control.right{href: "#myCarousel", "data-slide" => 'next'} &rsaquo;

.container-fluid
  .marketing
    .row-fluid
      .span4.offset1
        =link_to image_tag('presentation.png'), 'keocko_presentation.pdf'
        %h3 Download our detailed presentation
        =link_to 'Download pdf', 'keocko_presentation.pdf', class: 'more'
      .span4.offset2
        =link_to image_tag('contact.png'), contact_path
        %h3 Contact us for further information
        =link_to 'Contact details', contact_path, class: 'more'

app/views/pages/services.html.haml
- content_for(:title, "Keocko.com - Services")
.article-wrapper
  .container{style: 'max-width: 500px;'}
    :markdown
      ##Services

      >Human Sensor provides you statistics that you need
      >in order to reach your customers in a targeted way

      ####Fields of use
      retail, shopping centers, public spaces, community events

      - counting the passing / visiting traffic
      - measuring peak usage periods
      - workforce optimization
      - measuring customer satisfaction
      - reports on returning customers
      - customer habits
      - walked routes
      - comparative analyses


      ###Marketing, market research

      - target group analysis
      - campaign planning
      - measuring ads
      - analyzing campaigns
      - market research
      - comparative analyses

app/views/pages/solutions.html.haml
- content_for(:title, "Keocko.com - Solutions")
.article-wrapper
  .container{style: 'max-width: 500px;'}
    :markdown
      ##Solutions

      >Behavior and habits research –
      >the new level of customer
      >insight every moment


      By means of a special, biometric measuring algorithm,
      we can enter a new phase of customer insight,
      where all information is immediately available.

      Learning about the habits of your customers
      will gain you competitive advantage.

      ###Our mission:

      - To support your sales and marketing communication processes
      with measurable data.
      - Your customers are monitored 24/7, ensuring that
      you make the right decisions based on the information
      obtained through the technology.

      ###The system:

      - carries out facial recognition with more than 93% efficiency.

      The facial recognition technology

      - can:
        - divide the customers based on gender and age,
        - give real-time reports about it,
      - monitors the passing traffic,
      - can recognize the emotions of the detected
      person,
      - records the length of impression.

app/views/pages/technology.html.haml
- content_for(:title, "Keocko.com - Technology")
.article-wrapper
  .container{style: 'max-width: 500px;'}
    :markdown
      ##Technology

      >Behind the scenes

      - Have you ever thought of who usually visit your store?

      - Who look at your shop window?

      - How should you transform your business or shop window to best fit the customer needs?

      ####The customer base is constantly changing

      It is influenced by the season, the time period, the holidays and even the weather.

      In order to be up-to-date about customer needs all the time and profit the most from your business, you need an information tool that offers you the continuous view of your customers, analyses changes automatically and helps your work seven days a week, 24 hours a day.

      #####This is offered by Keocko.

      With our Human Sensor solution you receive accurate and continuous information about your customers in return for a minimum monthly charge.

      You are informed about how many people looked at your shop window, what is the gender ratio of your customers, which age group visits your store in which time period, you can even get information about what X or Y age group or baby boomers pay attention to, or how surprising a new shop window item is.

      We assist you in arranging and locating your business by showing the routes of the customers.

      Our company is at your service by applying the latest technology so you can make most out of your business premises, whether it is a single store or a chain of a global brand.